<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TrupeTargetFrameworks)</TargetFrameworks>
     <GenerateDocumentationFile>true</GenerateDocumentationFile>
     <Description>A lightweight, high-performance .NET actor model framework with supervision strategies, channel-based mailboxes, and AOT compatibility.</Description>
     <PackageTags>actor-model;actors;concurrency;message-passing;supervision;dotnet;trupe</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' != 'net462' OR '$(TargetFramework)' != 'netstandard2.0'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Trupe.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' OR  '$(TargetFramework)' == 'net462'">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="Microsoft.Bcl.HashCode" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trupe.Abstractions\Trupe.Abstractions.csproj" />
  </ItemGroup>
</Project>
